import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { prisma } from "@/lib/prisma";
import { requirePrivateUser, HttpError } from "@/lib/auth";
import { handleError } from "@/lib/http";
import { APP_NAME } from "@/lib/app-name";
import {
  computeFinancialYearByKey,
  getFinancialYearWindow,
  getVehicleExpenses,
} from "@/lib/taxes";
import { getSettings } from "@/lib/settings";

export const runtime = "nodejs";

// GET /api/taxes/export?fy=<startYear>
//
// Builds a print-ready PDF for the caller's My Taxes data in the chosen
// financial year. Layout:
//   • Cover header with FY label, owner name, generation timestamp.
//   • "FY at a glance" — category subtotals, vehicle subtotal, grand total.
//   • Per-category section listing every receipt + line item (date, vendor,
//     label, amount).
//   • "Vehicle expenses (Maintenance)" — auto-included service records for
//     vehicle-type maintenance items, grouped by vehicle.
//
// This is a *summary* document the user takes to their accountant. It does
// NOT embed receipt images or PDFs — those stay on disk and can be exported
// separately if needed.

type LineRow = {
  date: Date;
  vendor: string;
  label: string;
  amount: number;
};

function fmtMoney(n: number): string {
  return n.toLocaleString(undefined, {
    style: "currency",
    currency: "AUD",
    currencyDisplay: "narrowSymbol",
  });
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString("en-AU", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

export async function GET(req: NextRequest) {
  try {
    const me = await requirePrivateUser();
    const url = new URL(req.url);
    const fyKeyRaw = url.searchParams.get("fy");
    const settings = await getSettings();
    const fy =
      fyKeyRaw && /^\d{4}$/.test(fyKeyRaw)
        ? computeFinancialYearByKey(
            settings.financialYearStartMonth,
            settings.financialYearStartDay,
            Number(fyKeyRaw),
          )
        : await getFinancialYearWindow();

    const [receipts, categories, vehicleGroups] = await Promise.all([
      prisma.taxReceipt.findMany({
        where: {
          ownerId: me.id,
          date: {
            gte: new Date(fy.startISO),
            lt: new Date(fy.endExclusiveISO),
          },
        },
        include: { lineItems: { orderBy: { position: "asc" } } },
        orderBy: { date: "asc" },
      }),
      prisma.taxCategory.findMany({
        where: { ownerId: me.id },
        orderBy: [{ position: "asc" }, { createdAt: "asc" }],
      }),
      getVehicleExpenses({ ownerId: me.id, fy }),
    ]);

    if (!fy) throw new HttpError(500, "FY window unresolved");

    // Build a lookup of category id → display row, plus a "Uncategorised"
    // bucket for line items whose category was deleted.
    const catById = new Map(categories.map((c) => [c.id, c]));
    const linesByCat = new Map<string, LineRow[]>();
    const ensureBucket = (id: string) => {
      const cur = linesByCat.get(id);
      if (cur) return cur;
      const fresh: LineRow[] = [];
      linesByCat.set(id, fresh);
      return fresh;
    };

    for (const r of receipts) {
      for (const li of r.lineItems) {
        const key = li.categoryId ?? "__uncat";
        ensureBucket(key).push({
          date: r.date,
          vendor: r.vendor,
          label: li.label,
          amount: Number(li.amount),
        });
      }
    }

    // Sort each bucket by date for the section listings.
    for (const arr of linesByCat.values()) {
      arr.sort((a, b) => a.date.getTime() - b.date.getTime());
    }

    const grandTotal =
      Math.round(
        Array.from(linesByCat.values())
          .flat()
          .reduce((acc, r) => acc + r.amount, 0) * 100,
      ) / 100;

    const vehicleSubtotal =
      Math.round(
        vehicleGroups.reduce((acc, g) => acc + g.subtotal, 0) * 100,
      ) / 100;

    const pdfBuffer: Buffer = await new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: "A4", margin: 48 });
      const chunks: Buffer[] = [];
      doc.on("data", (c: Buffer) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err: Error) => reject(err));

      const pageRight = doc.page.width - doc.page.margins.right;
      const innerWidth = pageRight - doc.page.margins.left;

      // Header ------------------------------------------------------------
      doc.fontSize(22).fillColor("#111").text("My Taxes — Financial Year Summary");
      doc.moveDown(0.2);
      doc.fontSize(10).fillColor("#666").text(
        `${fy.label}  ·  ${me.name}  ·  Generated by ${APP_NAME}, ${new Date().toLocaleString("en-AU")}`,
      );
      doc.moveDown(0.5);
      doc
        .strokeColor("#e5e7eb")
        .lineWidth(1)
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(pageRight, doc.y)
        .stroke();
      doc.moveDown(0.75);

      // FY at a glance ----------------------------------------------------
      doc.fontSize(14).fillColor("#111").text("FY at a glance");
      doc.moveDown(0.3);

      const labelX = doc.page.margins.left;
      const amountX = pageRight - 110;
      const renderRow = (label: string, amount: number, bold = false) => {
        doc
          .fontSize(11)
          .fillColor(bold ? "#111" : "#222")
          .font(bold ? "Helvetica-Bold" : "Helvetica")
          .text(label, labelX, doc.y, { width: amountX - labelX - 10 });
        doc
          .fontSize(11)
          .fillColor(bold ? "#111" : "#222")
          .font(bold ? "Helvetica-Bold" : "Helvetica")
          .text(fmtMoney(amount), amountX, doc.y - doc.currentLineHeight(), {
            width: pageRight - amountX,
            align: "right",
          });
        doc.moveDown(0.2);
      };

      const catSubtotals = categories.map((c) => {
        const arr = linesByCat.get(c.id) ?? [];
        const subtotal =
          Math.round(arr.reduce((a, r) => a + r.amount, 0) * 100) / 100;
        return { c, subtotal };
      });

      // Hide rows with zero subtotal so the summary stays tight.
      for (const { c, subtotal } of catSubtotals) {
        if (subtotal === 0) continue;
        renderRow(c.name, subtotal);
      }

      const uncatLines = linesByCat.get("__uncat") ?? [];
      const uncatTotal =
        Math.round(uncatLines.reduce((a, r) => a + r.amount, 0) * 100) / 100;
      if (uncatTotal !== 0) renderRow("Uncategorised", uncatTotal);

      if (vehicleSubtotal !== 0) {
        renderRow("Vehicle (from Maintenance)", vehicleSubtotal);
      }

      doc.moveDown(0.2);
      doc
        .strokeColor("#cbd5e1")
        .lineWidth(0.5)
        .moveTo(labelX, doc.y)
        .lineTo(pageRight, doc.y)
        .stroke();
      doc.moveDown(0.2);
      renderRow(
        "Grand total (claimable)",
        Math.round((grandTotal + vehicleSubtotal) * 100) / 100,
        true,
      );
      doc.font("Helvetica");
      doc.moveDown(0.6);

      // Per-category sections --------------------------------------------
      const renderCategorySection = (title: string, lines: LineRow[]) => {
        if (lines.length === 0) return;
        // Soft page-break: if we're within 80pt of bottom, force a new page.
        if (doc.y > doc.page.height - doc.page.margins.bottom - 80) {
          doc.addPage();
        }
        const sub =
          Math.round(lines.reduce((a, r) => a + r.amount, 0) * 100) / 100;
        doc.fontSize(13).fillColor("#111").font("Helvetica-Bold")
          .text(`${title}  —  ${fmtMoney(sub)}`);
        doc.font("Helvetica");
        doc.moveDown(0.3);

        // Column header
        const dateCol = labelX;
        const vendorCol = labelX + 75;
        const labelCol = labelX + 215;
        const amtCol = pageRight - 70;
        doc.fontSize(9).fillColor("#666");
        doc.text("Date", dateCol, doc.y, { width: 70 });
        doc.text("Vendor", vendorCol, doc.y - doc.currentLineHeight(), {
          width: labelCol - vendorCol - 8,
        });
        doc.text("Item", labelCol, doc.y - doc.currentLineHeight(), {
          width: amtCol - labelCol - 8,
        });
        doc.text("Amount", amtCol, doc.y - doc.currentLineHeight(), {
          width: pageRight - amtCol,
          align: "right",
        });
        doc.moveDown(0.15);

        for (const r of lines) {
          if (doc.y > doc.page.height - doc.page.margins.bottom - 30) {
            doc.addPage();
          }
          doc.fontSize(10).fillColor("#111");
          doc.text(fmtDate(r.date), dateCol, doc.y, { width: 70 });
          doc.text(r.vendor, vendorCol, doc.y - doc.currentLineHeight(), {
            width: labelCol - vendorCol - 8,
            ellipsis: true,
          });
          doc.text(r.label, labelCol, doc.y - doc.currentLineHeight(), {
            width: amtCol - labelCol - 8,
            ellipsis: true,
          });
          doc.text(fmtMoney(r.amount), amtCol, doc.y - doc.currentLineHeight(), {
            width: pageRight - amtCol,
            align: "right",
          });
          doc.moveDown(0.15);
        }
        doc.moveDown(0.6);
      };

      for (const c of categories) {
        renderCategorySection(c.name, linesByCat.get(c.id) ?? []);
      }
      renderCategorySection("Uncategorised", linesByCat.get("__uncat") ?? []);

      // Vehicle section --------------------------------------------------
      if (vehicleGroups.length > 0) {
        if (doc.y > doc.page.height - doc.page.margins.bottom - 100) {
          doc.addPage();
        }
        doc.fontSize(13).fillColor("#111").font("Helvetica-Bold").text(
          `Vehicle expenses (Maintenance)  —  ${fmtMoney(vehicleSubtotal)}`,
        );
        doc.font("Helvetica");
        doc
          .fontSize(9)
          .fillColor("#666")
          .text(
            "Auto-pulled from the Maintenance log for any item set to Car or Motorbike.",
            { width: innerWidth },
          );
        doc.moveDown(0.4);

        for (const g of vehicleGroups) {
          if (doc.y > doc.page.height - doc.page.margins.bottom - 80) {
            doc.addPage();
          }
          doc
            .fontSize(11)
            .fillColor("#111")
            .font("Helvetica-Bold")
            .text(
              `${g.itemName}${g.identifier ? ` (${g.identifier})` : ""}  —  ${fmtMoney(g.subtotal)}`,
            );
          doc.font("Helvetica");
          doc.moveDown(0.15);

          for (const row of g.rows) {
            if (doc.y > doc.page.height - doc.page.margins.bottom - 30) {
              doc.addPage();
            }
            const labelText = `${row.workDone}${
              row.performedBy ? ` — ${row.performedBy}` : ""
            }`;
            doc.fontSize(10).fillColor("#111").text(
              fmtDate(row.servicedAt),
              labelX,
              doc.y,
              { width: 70 },
            );
            doc.text(labelText, labelX + 75, doc.y - doc.currentLineHeight(), {
              width: pageRight - 70 - (labelX + 75) - 8,
              ellipsis: true,
            });
            doc.text(
              fmtMoney(row.cost),
              pageRight - 70,
              doc.y - doc.currentLineHeight(),
              { width: 70, align: "right" },
            );
            doc.moveDown(0.15);
          }
          doc.moveDown(0.4);
        }
      }

      // Footer -----------------------------------------------------------
      doc.moveDown(0.5);
      doc
        .fontSize(8)
        .fillColor("#888")
        .text(
          "This export is for record-keeping only — the figures, categories, and inclusions are based on what you entered in My Taxes and what's logged in Maintenance. Confirm with a registered tax agent before lodging.",
          { width: innerWidth, align: "left" },
        );

      doc.end();
    });

    // v4.7.5 — Content-Disposition headers must be ByteString (≤ 0xFF). The
    // FY label uses an en-dash ("FY 2025–26") which is U+2013 / 8211, so
    // serialising it raw blew up with "Cannot convert argument to a
    // ByteString" the moment Next tried to write the header. Normalise the
    // ASCII filename and ALSO emit an RFC 5987 filename* with the original
    // (URL-encoded) string so modern browsers still get the pretty name.
    const prettyName = `my-taxes-${fy.label.replace(/\s+/g, "_")}-${me.name
      .replace(/\s+/g, "_")
      .toLowerCase()}.pdf`;
    const asciiName = prettyName
      .replace(/[‐-―]/g, "-") // U+2010..U+2015 dash family → ASCII hyphen
      .replace(/[^\x20-\x7E]/g, "_") // anything else non-ASCII → _
      .replace(/[\\/"]/g, "_");

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${asciiName}"; filename*=UTF-8''${encodeURIComponent(prettyName)}`,
        "Content-Length": String(pdfBuffer.length),
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    return handleError(e);
  }
}
